# Generated by Django 4.0.4 on 2022-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_userauth_rename_artistalbum_useralbum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbum',
            name='cover_art',
            field=models.FileField(upload_to='cover_art'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
