# Generated by Django 4.0.4 on 2022-06-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_useralbum_cover_art_alter_userdetail_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosession',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Producer', to='manager.userdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studiosession',
            name='end_time',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studiosession',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Artist', to='manager.userdetail'),
        ),
        migrations.AlterField(
            model_name='studiosession',
            name='start_time',
            field=models.TimeField(max_length=10),
        ),
    ]
